---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started

    - name: ustanovka php fpm
      apt: name=php-fpm

    - name: ustanovka sql
      apt: name=php-mysql

    - name: perezagruzka modulja vremeni
      systemd:
       name: systemd-timesyncd.service
       state: restarted

    - name: ustanovka modlja dlja importa sql dump
      apt: name=python3-pymysql

    - name: install python mysql bindings
      apt: name=python-mysqldb state=latest
      become: yes
      become_method: sudo
  #  - name: ustanovka modlja dlja importa sql dump 2
   #   apt: name=pymysql

    - name: Restore database
      mysql_db:
       name: mailserver
       state: import
       target: /home/ubuntu/conf_files/test.sql


