---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started

    #- name: restart time (perezagruzka)
    #  shell:
    #    cmd: sudo systemctl restart systemd-timesyncd.service

    - name: ustanovka php fpm
      apt: name=php-fpm

    - name: ustanovka sql
      apt: name=php-mysql

    - name: reload service httpd, in all cases
      systemd:
       name: systemd-timesyncd.service
       state: restarted
